server:
  port: 5000
spring:
  application:
    name: sardine-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:5000/eureka
    register-with-eureka: false # 不注册自己
    fetch-registry: false