spring:
  profiles:
    active: 01

---
server:
  port: 5001
spring:
  application:
    name: sardine-registry
  profiles: 01
eureka:
  instance:
    hostname: eureka1.com
  client:
    service-url:
      defaultZone: http://eureka2.com:5002/eureka
#    register-with-eureka: false # 不注册自己
#    fetch-registry: false

---
server:
  port: 5002
spring:
  application:
    name: sardine-registry
  profiles: 02
eureka:
  instance:
    hostname: eureka2.com
  client:
    service-url:
      defaultZone: http://eureka1.com:5001/eureka
#    register-with-eureka: false # 不注册自己
#    fetch-registry: false