spring:
  profiles:
    active: single

---
server:
  port: 5000
spring:
  application:
    name: sardine-registry
  profiles: single
eureka:
  instance:
    hostname: eureka1.com
  client:
    service-url:
      defaultZone: http://eureka1.com:5000/eureka
    register-with-eureka: false # 单节点的 eureka 不注册自己
    fetch-registry: false

---
server:
  port: 5001
spring:
  application:
    name: sardine-registry
  profiles: eu01
eureka:
  instance:
    hostname: eureka1.com
  client:
    service-url:
      defaultZone: http://eureka2.com:5002/eureka

---
server:
  port: 5002
spring:
  application:
    name: sardine-registry
  profiles: eu02
eureka:
  instance:
    hostname: eureka2.com
  client:
    service-url:
      defaultZone: http://eureka1.com:5001/eureka