server:
  port: 8001
spring:
  application:
    name: sardine-cookbook
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.97.116.169:3306/tripper?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:5000/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
