server:
  port: 8001
spring:
  application:
    name: sardine-cookbook
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.97.116.169:3306/tripper?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
ribbon:
  ConnectTimeout: 1000            # ribbon连接超时时长
  ReadTimeout: 3000               # ribbon读取超时时长
  MaxAutoRetries: 1               # 当前服务重试次数
  MaxAutoRetriesNextServer: 1     # 切换服务重试次数
  OkToRetryOnAllOperations: false # 是否所有操作都重试
  MaxTotalConnections: 500        # 最大连接数
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
hystrix:
  dashboard:
    proxy-stream-allow-list: '*'