server:
  port: 5004
spring:
  application:
    name: sardine-sms
  rabbitmq:
    host: 47.97.116.169
    username: admin
    password: admin
    virtual-host: sardine
  redis:
    host: 47.97.116.169
sardine:
  aliyun:
    sms:
      sign-name: sardine
      template-code: SMS_175532645
      access-key-id: LTAI4Ft2uBoT3jmgsCeqhgWS
      access-key-secret: gnkRFKUH06iqJdHpBFEx0c7m65grZe