server:
  port: 5004
spring:
  application:
    name: sardine-sms
  rabbitmq:
    host: 47.97.116.169
    username: admin
    password: admin
    virtual-host: sardine
  redis:
    host: 47.97.116.169
sardine:
  sms:
    accessKeyId: LTAI4Ft2uBoT3jmgsCeqhgWS
    accessKeySecret: gnkRFKUH06iqJdHpBFEx0c7m65grZe
    signName: sardine
    templateCode: SMS_175532645