server:
  port: 12346
dubbo:
  application:
    name: consumer-service
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20992
  consumer:
    timeout: 3000