server:
  port: 5001
spring:
  application:
    name: sardine-gateway
  cloud:
    gateway:
      routes:
        - id: my-route
          uri: http://localhost:7012
          predicates:
            - Path=/gateway/**      # 将后缀是此路径的转发到uri
          filters:
            - StripPrefix=1         # 去掉1个前缀
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:7000/eureka
sardine:
  gateway:
    auth:
      allowed-paths:
        - /api/user
