server:
  port: 5003
spring:
  application:
    name: sardine-file
eureka:
  client:
    service-url:
      defaultZone: http://47.97.116.169:5000/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true